---
title: "Boosted Forest Model - Music Genre Classification"
author: "Kabir Snell"
date: "2022-11-30"
output: html_document
---
```{R message = FALSE}
# Loading Libraries
library(tidyverse)
library(tidymodels)
library(ISLR)
library(rpart.plot)
library(vip)
library(janitor)
library(randomForest)
library(xgboost)
library(ranger)
library(corrplot)
```

```{R}
# Reading in the data
genre <- read.csv('../data/processed/processed_data.csv', stringsAsFactors = TRUE)
```

```{R}
# Splitting the data
set.seed(727)

genre_split <- initial_split(genre, prop = .8)

genre_train <- training(genre_split)
genre_test <- testing(genre_split)
```

```{R}
# Creating 8 fold validation
genre_fold <- vfold_cv(genre_train, v = 8, strata = music_genre)
```

```{R}
# Creating Recipe
genre_recipe <- recipe(music_genre ~ popularity + acousticness + danceability + duration_ms + energy + instrumentalness + liveness + loudness + mode + speechiness + tempo + key, data = genre_train) %>%
  step_dummy(mode) %>%
  step_dummy(key) %>%
  step_normalize(all_predictors())
```

```{R}
tree_spec <- decision_tree() %>%
  set_engine("rpart")

class_tree_spec <- tree_spec %>%
  set_mode("classification")

tree_workflow <- workflow() %>%
  add_recipe(genre_recipe) %>%
  add_model(class_tree_spec %>% set_args(cost_complexity = tune()))

tree_grid <- grid_regular(cost_complexity(range = c(-3, -1)), levels = 15)
```

```{R}
tree_tune <- tune_grid(
  tree_workflow,
  resamples = genre_fold,
  grid = tree_grid, 
  metrics = metric_set(accuracy, mn_log_loss, roc_auc)
)

write_rds(tree_tune, file = "tree.rds")
```

```{R}
tree_tune <- read_rds(file = "tree.rds")

autoplot(tree_tune)
```

```{R}
tree_tune %>%
  collect_metrics()
```

```{R}
best_tree <- select_best(tree_tune, metric = "accuracy")

class_tree_final <- finalize_workflow(tree_workflow, best_tree)

class_tree_fit <- fit(class_tree_final, data = genre_train)

final_tibble <- augment(class_tree_fit, new_data = genre_test)

final_tibble %>% 
  accuracy(truth = music_genre, estimate = .pred_class)

final_tibble %>% 
  mn_log_loss(truth = music_genre, estimate = .pred_Alternative:.pred_Rock)

final_tibble %>% 
  roc_auc(truth = music_genre, estimate = .pred_Alternative:.pred_Rock)
```

```{R}
all_roc_curves <- final_tibble %>% 
  roc_curve(truth = music_genre, estimate = .pred_Alternative:.pred_Rock) %>% 
  autoplot()
all_roc_curves
```

```{r}
confusion_matrix <- final_tibble %>%
  conf_mat(music_genre, .pred_class) %>% 
  autoplot(type = "heatmap")
confusion_matrix
```

```{R}
final_tibble %>%
  accuracy(truth = music_genre, estimate = .pred_class)
```

```{R}
final_accuracy <- final_tibble %>%
  as.data.frame() %>%
  group_by(music_genre) %>%
  accuracy(truth = music_genre, estimate = .pred_class) %>%
  select(music_genre, .metric, .estimate)

final_accuracy
```

```{R}
final_accuracy %>%
  ggplot(aes(x = music_genre, fill = music_genre, y = .estimate)) +
  geom_col() +
  scale_fill_brewer(palette = "Spectral")
```

============================================================================================

```{R}
# Boosted forest spec
boosted_spec <- boost_tree(trees = tune()) %>%
  set_engine("xgboost") %>%
  set_mode("classification")

# Boosted forest workflow
boosted_workflow <- workflow() %>% 
  add_recipe(genre_recipe) %>% 
  add_model(boosted_spec)

# Boosted forest parameter grid
boosted_grid <- grid_regular(trees(range = c(10, 500)), levels = 8)
```

```{r eval=FALSE}
# Tuning Grid
boosted_tune <- tune_grid(
  boosted_workflow,
  resamples = genre_fold,
  grid = boosted_grid,
  metrics = metric_set(accuracy, mn_log_loss, roc_auc)
)

# Writing rds file
write_rds(boosted_tune, file = "boosted.rds")
```

```{R}
boosted_tune <- read_rds(file = "boosted.rds")
autoplot(boosted_tune)
```

```{R}
boosted_tune %>% 
  collect_metrics()
```

```{R}
best <- select_best(boosted_tune, metric = "mn_log_loss")

final_workflow <- finalize_workflow(boosted_workflow, best)

final_fit <- fit(final_workflow, data = genre_train)

final_tibble <- augment(final_fit, new_data = genre_test)

final_tibble %>% 
  accuracy(truth = music_genre, estimate = .pred_class)

final_tibble %>% 
  mn_log_loss(truth = music_genre, estimate = .pred_Alternative:.pred_Rock)

final_tibble %>% 
  roc_auc(truth = music_genre, estimate = .pred_Alternative:.pred_Rock)
```

```{R}
all_roc_curves <- final_tibble %>% 
  roc_curve(truth = music_genre, estimate = .pred_Alternative:.pred_Rock) %>% 
  autoplot()
all_roc_curves
```

```{r}
confusion_matrix <- final_tibble %>%
  conf_mat(music_genre, .pred_class) %>% 
  autoplot(type = "heatmap")
confusion_matrix
```

```{R}
final_accuracy <- final_tibble %>%
  as.data.frame() %>%
  group_by(music_genre) %>%
  accuracy(truth = music_genre, estimate = .pred_class) %>%
  select(music_genre, .metric, .estimate)

final_accuracy
```

```{R}
final_accuracy %>%
  ggplot(aes(x = music_genre, fill = music_genre, y = .estimate)) +
  geom_col() +
  scale_fill_brewer(palette = "Spectral")
```


================================================================
Random Forest

```{R}
rf_spec <- rand_forest(mtry = tune(), trees = tune(), min_n = tune()) %>% 
  set_engine("ranger", importance = "impurity") %>% 
  set_mode("classification")

rf_workflow <- workflow() %>%
  add_recipe(genre_recipe) %>%
  add_model(rf_spec)

rf_parameter_grid <- grid_regular(mtry(range = c(1, 5)), trees(range = c(1,500)), min_n(range = c(1,8)), levels = 4)
```

```{R, eval = FALSE}
rf_tune_res <- tune_grid(
  rf_workflow,
  resamples = genre_fold,
  grid = rf_parameter_grid,
  metrics = metric_set(accuracy, mn_log_loss, roc_auc)
)

write_rds(rf_tune_res, file = "rf.rds")
```

```{r}
rf_tune <- read_rds(file = "rf.rds")

autoplot(rf_tune)
```

```{R}
rf_tune %>%
  collect_metrics()
```


```{R}
best_rf <- select_best(rf_tune, metric = "mn_log_loss")

rf_final <- finalize_workflow(rf_workflow, best_rf)

rf_fit <- fit(rf_final, data = genre_train)

final_tibble <- augment(rf_fit, new_data = genre_test)

final_tibble %>% 
  accuracy(truth = music_genre, estimate = .pred_class)

final_tibble %>% 
  mn_log_loss(truth = music_genre, estimate = .pred_Alternative:.pred_Rock)

final_tibble %>% 
  roc_auc(truth = music_genre, estimate = .pred_Alternative:.pred_Rock)
```

```{R}
all_roc_curves <- final_tibble %>% 
  roc_curve(truth = music_genre, estimate = .pred_Alternative:.pred_Rock) %>% 
  autoplot()
all_roc_curves
```

```{r}
confusion_matrix <- final_tibble %>%
  conf_mat(music_genre, .pred_class) %>% 
  autoplot(type = "heatmap")
confusion_matrix
```

```{R}
final_accuracy <- final_tibble %>%
  as.data.frame() %>%
  group_by(music_genre) %>%
  accuracy(truth = music_genre, estimate = .pred_class) %>%
  select(music_genre, .metric, .estimate)

final_accuracy
```

```{R}
final_accuracy %>%
  ggplot(aes(x = music_genre, fill = music_genre, y = .estimate)) +
  geom_col() +
  scale_fill_brewer(palette = "Spectral")
```












